### PR TITLE
Handling accents

### PR DESCRIPTION
**Pull request by msalo3**
This is a potentially big change. 

We could use this in each class, but I'm bringing up the idea to build out the whole payload and use it on that. 

Might not be a good idea to loop over a gigantic payload?

Let me know what you think!

### CODE REVIEW

**Comment by raysapida** [comment]
I'm still a little hazy on encoding in quickbooks but if the string is being treated as Unicode characters, we could potential gsub for the different types of accent marks and remove them.

https://unicode-table.com/en/blocks/combining-diacritical-marks/

**Comment by gorandev** [comment]
I'd look for a library or gem to help with this. No need to reinvent the wheel!

**Comment by gorandev** [comment]
All hail StackOverflow: https://stackoverflow.com/questions/15686752/ruby-method-to-remove-accents-from-utf-8-international-characters

```
1.9.3p392 :001 > require "i18n"
 => true
1.9.3p392 :002 > I18n.transliterate("Hé les mecs!")
 => "He les mecs!"
```

Apparently it breaks with chinese characters (turns 'em into question marks) but that's outside of the scope of this PR, right?

**Comment by msalo3** [comment]
Both great ideas. I need to add that i18n and update the PR, but a really big question in this PR is about doing this here in the code or should we do it on each class? Not sure the right way. I'd like @bcgianni to weigh in too because he knows QBE probably the best.

**Pull request closed without merging**
