### PR TITLE
Feature/backslashes

### PR DESCRIPTION
**Pull request by raysapida**

### CODE REVIEW

**Review by gorandev — APPROVED** [review]

**Comment by msalo3** [comment]
Are we just removing backslashes here? What about when getting objects from QBE? Won't it break there too?

**Comment by raysapida** [comment]
> Are we just removing backslashes here? What about when getting objects from QBE? Won't it break there too?

I'm not sure about that part but I'll try to see if it breaks in the Amazon workspace. From what I could tell, the save method for the object use `#id_for_object` to save the file name for inserts and updates. When we query for stuff though, they're either saving file names by the object ref or list id so they don't have the same issue with backslashes.

**Comment by bcgianni** [comment]
It might duplicate objects if we remove backslashes on the way to qbe and import it back to flowlink with -backslash-

**Comment by raysapida** [comment]
> It might duplicate objects if we remove backslashes on the way to qbe and import it back to flowlink with -backslash-

From what I could tell, the id for object is only used to create the file name and the id and names are left the same?

**Review by msalo3 — APPROVED** [review]

**Pull request merged**
